# Generated by Django 5.2.1 on 2025-11-11 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_website_font_family_alter_website_footer_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='header_content',
        ),
        migrations.RemoveField(
            model_name='website',
            name='main_content',
        ),
        migrations.AddField(
            model_name='website',
            name='footer_background_color',
            field=models.CharField(default='#f3f4f6', max_length=7, verbose_name='Цвет фона Footer'),
        ),
        migrations.AddField(
            model_name='website',
            name='footer_show',
            field=models.BooleanField(default=True, verbose_name='Показывать Footer'),
        ),
        migrations.AddField(
            model_name='website',
            name='footer_text_color',
            field=models.CharField(default='#000000', max_length=7, verbose_name='Цвет текста Footer'),
        ),
        migrations.AddField(
            model_name='website',
            name='header_background_color',
            field=models.CharField(default='#ffffff', max_length=7, verbose_name='Цвет фона Header'),
        ),
        migrations.AddField(
            model_name='website',
            name='header_company_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Название компании'),
        ),
        migrations.AddField(
            model_name='website',
            name='header_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Логотип'),
        ),
        migrations.AddField(
            model_name='website',
            name='header_show',
            field=models.BooleanField(default=True, verbose_name='Показывать Header'),
        ),
        migrations.AddField(
            model_name='website',
            name='header_text_color',
            field=models.CharField(default='#000000', max_length=7, verbose_name='Цвет текста Header'),
        ),
        migrations.AlterField(
            model_name='website',
            name='font_family',
            field=models.CharField(default='Arial, sans-serif', max_length=100, verbose_name='Шрифт'),
        ),
        migrations.AlterField(
            model_name='website',
            name='footer_content',
            field=models.TextField(blank=True, default='<p>© 2024 Мой сайт</p>', verbose_name='Содержимое Footer'),
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('text', 'Текст'), ('heading', 'Заголовок'), ('image', 'Изображение'), ('video', 'Видео'), ('button', 'Кнопка'), ('slider', 'Слайдер'), ('section', 'Секция')], max_length=50, verbose_name='Тип блока')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('data', models.JSONField(default=dict, verbose_name='Данные блока')),
                ('background_color', models.CharField(blank=True, max_length=7, null=True, verbose_name='Цвет фона')),
                ('text_color', models.CharField(blank=True, max_length=7, null=True, verbose_name='Цвет текста')),
                ('padding', models.CharField(default='20px', max_length=50, verbose_name='Отступы')),
                ('margin', models.CharField(default='0', max_length=50, verbose_name='Внешние отступы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='base.website', verbose_name='Сайт')),
            ],
            options={
                'verbose_name': 'Блок',
                'verbose_name_plural': 'Блоки',
                'ordering': ['order'],
            },
        ),
    ]
