# Generated by Django 5.2.8 on 2025-11-08 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название сайта')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('background_color', models.CharField(default='#ffffff', max_length=7, verbose_name='Цвет фона')),
                ('text_color', models.CharField(default='#000000', max_length=7, verbose_name='Цвет текста')),
                ('header_content', models.TextField(blank=True, verbose_name='Заголовок')),
                ('main_content', models.TextField(blank=True, verbose_name='Основной контент')),
                ('footer_content', models.TextField(blank=True, verbose_name='Футер')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Сайт',
                'verbose_name_plural': 'Сайты',
            },
        ),
    ]
