# Generated by Django 5.2.8 on 2025-11-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='font_family',
            field=models.CharField(default='Arial, sans-serif', max_length=50, verbose_name='Шрифт'),
        ),
        migrations.AlterField(
            model_name='website',
            name='footer_content',
            field=models.TextField(blank=True, default='<p>© 2024 Мой сайт</p>', verbose_name='Футер'),
        ),
        migrations.AlterField(
            model_name='website',
            name='header_content',
            field=models.TextField(blank=True, default='<h1>Заголовок сайта</h1>', verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='website',
            name='main_content',
            field=models.TextField(blank=True, default='<p>Добро пожаловать на мой сайт!</p>', verbose_name='Основной контент'),
        ),
        migrations.AlterField(
            model_name='website',
            name='title',
            field=models.CharField(default='Мой сайт', max_length=200, verbose_name='Название сайта'),
        ),
    ]
