# Generated by Django 5.2.1 on 2025-11-11 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_website_header_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blocks/images/', verbose_name='Изображение'),
        ),
    ]
